### ISSUE TITLE
致命bug-

### ISSUE THREAD

**Issue by coffeehb** [cckuailong/hostscan#1]
复现验证命令：
./main -i 120.133.132.77 -d xxoo.vivo.com.cn

-D -I 参数也是一样的。不知道是哪儿的问题，HOST碰撞请求构造是错的。
![image](https://user-images.githubusercontent.com/5829776/137661018-8d933442-d2c3-43d4-b188-c72cd85c75d7.png)

**Comment by cckuailong** [comment]
新版本应该已经修复了
