### ISSUE TITLE
进程被kill

### ISSUE THREAD

**Issue by WULINPIN** [cckuailong/hostscan#6]
师傅，我的host文件大概有19w行，运行直接被kill是什么原因
系统环境：
Linux kali 5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux
![微信图片_20230213113323](https://user-images.githubusercontent.com/30523752/218364547-457e5d76-1bfd-44d9-abf5-d124607b5be7.png)

**Comment by cckuailong** [comment]
是不是内存爆了，因为代码的逻辑是全量读到内存中，没有分批处理的逻辑

**Comment by cckuailong** [comment]
> 是不是内存爆了，因为代码的逻辑是全量读到内存中，没有分批处理的逻辑

近期我会针对这种情况做一个流处理的适配和改进，保证大文件读取的稳定性

**Comment by cckuailong** [comment]
请使用最新版本试一下
