### ISSUE TITLE
行数计算截取有问题，少了一行。

### ISSUE THREAD

**Issue by Laura0xiaoshizi** [cckuailong/hostscan#9]
<img width="985" alt="图片" src="https://github.com/cckuailong/hostscan/assets/31725824/d080ed01-7eb7-44db-9973-9c8b6f900387">

都少算了一行。

**Comment by cckuailong** [comment]
原逻辑为判断换行的数量，所以需要文件最后一行为空行

0.2.3版本已适配此issue中最后无空行的情况
